"""
LAIS - Linux AI Security Toolkit
Demo Environments: Pre-built AI deployment scenarios for demonstration.
Author: Larry Odeyemi

Three scenarios:
  1. Enterprise AI Chatbot — customer-facing LLM with CRM integration
  2. AI-Powered SOC — LLM-assisted threat analysis with agentic response
  3. AI in OT/ICS — ML predictive maintenance + LLM operator assistant (Larry's differentiator)
"""

from typing import List, Optional
from ai_model import AIEnvironment, AIAsset, AIAssetType


def _build_enterprise_scenario() -> AIEnvironment:
    """Scenario 1: Enterprise AI Chatbot — many vulnerabilities, no governance."""
    return AIEnvironment(
        id="env_enterprise",
        name="Enterprise AI Chatbot (Startup Inc.)",
        description="A fast-growing startup deployed a customer-facing LLM chatbot with CRM integration, plus employees using personal AI tools without approval. No AI governance policies exist.",
        organization="Startup Inc.",
        environment_type="enterprise",
        assets=[
            AIAsset(
                id="asset_chatbot",
                name="Customer Support Chatbot",
                asset_type=AIAssetType.LLM_CHATBOT,
                description="GPT-4 powered customer support chatbot integrated with CRM database and order management system.",
                model_provider="OpenAI",
                deployment_env="enterprise",
                has_tool_access=False,
                has_data_access=True,
                has_internet_access=False,
                is_customer_facing=True,
                is_safety_critical=False,
                integrations=["CRM Database", "Order Management", "Email System"],
                data_sources=["Customer records", "Order history", "Support tickets"],
                access_controls={
                    "input_filtering": False,
                    "output_filtering": False,
                    "system_prompt_isolation": False,
                    "jailbreak_detection": False,
                    "rate_limiting": True,
                    "cost_controls": False,
                    "token_limits": False,
                    "content_filtering": False,
                    "output_validation": False,
                    "conversation_monitoring": False,
                },
            ),
            AIAsset(
                id="asset_internal_assistant",
                name="Internal AI Assistant",
                asset_type=AIAssetType.LLM_AGENT,
                description="AI assistant with access to internal tools: email, calendar, file sharing, and HR system.",
                model_provider="Anthropic",
                deployment_env="enterprise",
                has_tool_access=True,
                has_data_access=True,
                has_internet_access=True,
                is_customer_facing=False,
                is_safety_critical=False,
                integrations=["Email", "Calendar", "SharePoint", "HR System"],
                data_sources=["Employee records", "Internal documents", "Email"],
                access_controls={
                    "input_filtering": False,
                    "output_filtering": False,
                    "system_prompt_isolation": False,
                    "jailbreak_detection": False,
                    "tool_use_guardrails": False,
                    "human_in_the_loop": False,
                    "rate_limiting": False,
                    "cost_controls": False,
                    "token_limits": False,
                    "content_filtering": False,
                    "conversation_monitoring": False,
                },
            ),
        ],
        governance_policies={
            "ai_governance_policy": False,
            "ai_risk_ownership": False,
            "ai_acceptable_use_policy": False,
            "ai_incident_response": False,
            "ai_ethics_review": False,
            "ai_inventory": False,
            "data_lineage_tracking": False,
            "stakeholder_mapping": False,
            "ai_data_classification": False,
            "model_performance_monitoring": False,
            "bias_testing": False,
            "ai_security_testing": False,
            "output_quality_metrics": False,
            "trustworthiness_assessment": False,
            "ai_risk_mitigation": False,
            "ai_continuous_monitoring": False,
            "model_lifecycle_management": False,
            "third_party_ai_risk": False,
            "model_provenance_tracking": False,
            "dependency_scanning": False,
            "vendor_security_assessment": False,
            "uses_rag": False,
            "output_fact_checking": False,
            "response_grounding": False,
            "data_validation_pipeline": False,
        },
        shadow_ai_indicators=[
            {
                "type": "network_traffic",
                "target": "api.openai.com",
                "source_ip": "10.0.1.45",
                "user": "jsmith",
                "description": "Employee using personal ChatGPT account to draft company emails with customer data",
                "evidence": "DNS query log: api.openai.com from 10.0.1.45 (jsmith workstation), 47 requests in 24h",
            },
            {
                "type": "network_traffic",
                "target": "claude.ai",
                "source_ip": "10.0.1.67",
                "user": "mwilson",
                "description": "Marketing team using Claude to analyze competitive intelligence documents",
                "evidence": "Proxy log: HTTPS POST to claude.ai from 10.0.1.67, large payload (confidential docs uploaded)",
            },
            {
                "type": "endpoint_process",
                "target": "chatgpt-extension",
                "source_ip": "10.0.1.22",
                "user": "agarcia",
                "description": "Unauthorized ChatGPT browser extension installed on finance workstation",
                "evidence": "Endpoint scan: Chrome extension 'ChatGPT for Chrome' detected on finance-ws-03, has access to all page content",
            },
            {
                "type": "network_traffic",
                "target": "copilot-proxy",
                "source_ip": "10.0.1.88",
                "user": "developer1",
                "description": "Developer using personal GitHub Copilot license with corporate source code",
                "evidence": "Proxy log: copilot-proxy.githubusercontent.com from dev workstation, code completion telemetry detected",
            },
        ],
    )


def _build_soc_scenario() -> AIEnvironment:
    """Scenario 2: AI-Powered SOC — partial controls, agentic risks."""
    return AIEnvironment(
        id="env_soc",
        name="AI-Powered SOC (SecureCorp)",
        description="A mid-size security operations center deployed AI for alert triage and threat analysis. Some controls exist but agentic AI risks are not addressed. Uses RAG for knowledge base.",
        organization="SecureCorp",
        environment_type="soc",
        assets=[
            AIAsset(
                id="asset_soc_analyst",
                name="AI SOC Analyst",
                asset_type=AIAssetType.LLM_AGENT,
                description="LLM-assisted SOC analyst that triages alerts, enriches IOCs, and drafts incident reports. Has tool access to SIEM, threat intel feeds, and ticketing system.",
                model_provider="OpenAI",
                deployment_env="soc",
                has_tool_access=True,
                has_data_access=True,
                has_internet_access=True,
                is_customer_facing=False,
                is_safety_critical=False,
                integrations=["Splunk SIEM", "MISP Threat Intel", "ServiceNow", "VirusTotal"],
                data_sources=["Security logs", "Alert data", "Threat intel feeds", "Incident reports"],
                access_controls={
                    "input_filtering": True,
                    "output_filtering": True,
                    "system_prompt_isolation": True,
                    "jailbreak_detection": False,
                    "tool_use_guardrails": True,
                    "human_in_the_loop": False,
                    "rate_limiting": True,
                    "cost_controls": True,
                    "token_limits": True,
                    "content_filtering": True,
                    "output_validation": False,
                    "conversation_monitoring": False,
                },
            ),
            AIAsset(
                id="asset_auto_responder",
                name="Automated Incident Responder",
                asset_type=AIAssetType.LLM_AGENT,
                description="AI agent that can automatically execute incident response actions: block IPs on firewall, disable accounts in AD, isolate endpoints.",
                model_provider="Anthropic",
                deployment_env="soc",
                has_tool_access=True,
                has_data_access=True,
                has_internet_access=False,
                is_customer_facing=False,
                is_safety_critical=False,
                integrations=["Palo Alto Firewall", "Azure AD", "CrowdStrike Falcon", "ServiceNow"],
                data_sources=["SIEM alerts", "EDR telemetry", "Firewall logs"],
                access_controls={
                    "input_filtering": True,
                    "output_filtering": False,
                    "system_prompt_isolation": True,
                    "jailbreak_detection": False,
                    "tool_use_guardrails": False,
                    "human_in_the_loop": False,
                    "rate_limiting": True,
                    "cost_controls": True,
                    "token_limits": True,
                    "content_filtering": False,
                    "output_validation": False,
                    "conversation_monitoring": False,
                },
            ),
        ],
        governance_policies={
            "ai_governance_policy": True,
            "ai_risk_ownership": True,
            "ai_acceptable_use_policy": True,
            "ai_incident_response": False,
            "ai_ethics_review": False,
            "ai_inventory": True,
            "data_lineage_tracking": False,
            "stakeholder_mapping": False,
            "ai_data_classification": True,
            "model_performance_monitoring": True,
            "bias_testing": False,
            "ai_security_testing": False,
            "output_quality_metrics": False,
            "trustworthiness_assessment": False,
            "ai_risk_mitigation": True,
            "ai_continuous_monitoring": True,
            "model_lifecycle_management": False,
            "third_party_ai_risk": True,
            "model_provenance_tracking": True,
            "dependency_scanning": True,
            "vendor_security_assessment": True,
            "uses_rag": True,
            "embedding_access_controls": False,
            "output_fact_checking": False,
            "response_grounding": True,
            "data_validation_pipeline": False,
        },
        shadow_ai_indicators=[
            {
                "type": "network_traffic",
                "target": "perplexity.ai",
                "source_ip": "10.0.5.12",
                "user": "analyst1",
                "description": "SOC analyst using Perplexity to research IOCs instead of approved threat intel tools",
                "evidence": "DNS log: perplexity.ai from SOC workstation, queries contain internal IOC data",
            },
        ],
    )


def _build_ot_ics_scenario() -> AIEnvironment:
    """Scenario 3: AI in OT/ICS — critical infrastructure, maximum risk."""
    return AIEnvironment(
        id="env_ot_ics",
        name="AI in OT/ICS Critical Infrastructure (ChemPlant Corp)",
        description="A chemical manufacturing plant deployed ML-based predictive maintenance on industrial equipment and an LLM-powered operator assistant connected to SCADA/DCS systems. Minimal AI security controls. This represents the highest-risk scenario.",
        organization="ChemPlant Corp",
        environment_type="ot_ics",
        assets=[
            AIAsset(
                id="asset_pred_maint",
                name="Predictive Maintenance ML Model",
                asset_type=AIAssetType.PREDICTIVE_MAINTENANCE,
                description="ML model analyzing vibration, temperature, and pressure sensor data from rotating equipment to predict failures before they occur.",
                model_provider="In-house (TensorFlow)",
                deployment_env="ot_ics",
                has_tool_access=False,
                has_data_access=True,
                has_internet_access=False,
                is_customer_facing=False,
                is_safety_critical=True,
                integrations=["Historian Server", "SCADA System", "CMMS"],
                data_sources=["Vibration sensors", "Temperature sensors", "Pressure sensors", "Historian logs"],
                access_controls={
                    "input_filtering": False,
                    "output_filtering": False,
                    "system_prompt_isolation": False,
                    "rate_limiting": False,
                    "cost_controls": False,
                    "token_limits": False,
                    "output_validation": False,
                    "safety_interlocks": False,
                },
            ),
            AIAsset(
                id="asset_operator_assistant",
                name="AI Operator Assistant",
                asset_type=AIAssetType.AI_ASSISTANT,
                description="LLM-powered operator assistant that can answer questions about SOPs, alarm conditions, and suggest operational adjustments. Connected to DCS for read access.",
                model_provider="OpenAI",
                deployment_env="ot_ics",
                has_tool_access=True,
                has_data_access=True,
                has_internet_access=False,
                is_customer_facing=False,
                is_safety_critical=True,
                integrations=["DCS System", "Alarm Management", "SOP Database", "Historian"],
                data_sources=["Operating procedures", "Alarm history", "Process parameters", "Safety data sheets"],
                access_controls={
                    "input_filtering": False,
                    "output_filtering": False,
                    "system_prompt_isolation": False,
                    "jailbreak_detection": False,
                    "tool_use_guardrails": False,
                    "human_in_the_loop": False,
                    "rate_limiting": False,
                    "cost_controls": False,
                    "token_limits": False,
                    "content_filtering": False,
                    "output_validation": False,
                    "conversation_monitoring": False,
                    "safety_interlocks": False,
                },
            ),
            AIAsset(
                id="asset_anomaly_detection",
                name="OT Network Anomaly Detection",
                asset_type=AIAssetType.ANOMALY_DETECTION,
                description="ML-based network anomaly detection monitoring Modbus/TCP and EtherNet/IP traffic for suspicious patterns.",
                model_provider="In-house (scikit-learn)",
                deployment_env="ot_ics",
                has_tool_access=False,
                has_data_access=True,
                has_internet_access=False,
                is_customer_facing=False,
                is_safety_critical=True,
                integrations=["OT Network TAP", "SIEM", "SOC Dashboard"],
                data_sources=["Modbus/TCP traffic", "EtherNet/IP traffic", "Network flow data"],
                access_controls={
                    "input_filtering": False,
                    "output_filtering": False,
                    "rate_limiting": False,
                    "output_validation": False,
                    "safety_interlocks": False,
                },
            ),
        ],
        governance_policies={
            "ai_governance_policy": False,
            "ai_risk_ownership": False,
            "ai_acceptable_use_policy": False,
            "ai_incident_response": False,
            "ai_ethics_review": False,
            "ai_inventory": False,
            "data_lineage_tracking": False,
            "stakeholder_mapping": False,
            "ai_data_classification": False,
            "model_performance_monitoring": False,
            "bias_testing": False,
            "ai_security_testing": False,
            "output_quality_metrics": False,
            "trustworthiness_assessment": False,
            "ai_risk_mitigation": False,
            "ai_continuous_monitoring": False,
            "model_lifecycle_management": False,
            "third_party_ai_risk": False,
            "model_provenance_tracking": False,
            "dependency_scanning": False,
            "vendor_security_assessment": False,
            "uses_rag": False,
            "output_fact_checking": False,
            "response_grounding": False,
            "data_validation_pipeline": False,
            # OT-specific AI controls — all missing
            "ot_ai_predictive_maintenance_security": False,
            "ot_ai_anomaly_detection_integrity": False,
            "ot_ai_no_write_access_plc": False,
            "ot_ai_llm_scada_controls": False,
            "ot_ai_no_autonomous_safety_decisions": False,
            "ot_ai_training_data_protection": False,
            "ot_ai_network_segmentation": False,
        },
        shadow_ai_indicators=[
            {
                "type": "endpoint_process",
                "target": "ollama",
                "source_ip": "10.0.3.55",
                "user": "eng_maint",
                "description": "Maintenance engineer running self-hosted LLM (Ollama) on an OT engineering workstation to analyze equipment logs",
                "evidence": "Process scan: ollama process running on ENG-WS-03 in OT network, model: llama3, processing historian data",
            },
            {
                "type": "network_traffic",
                "target": "api.openai.com",
                "source_ip": "10.0.3.60",
                "user": "operator2",
                "description": "Control room operator sending process alarm data to ChatGPT for troubleshooting assistance",
                "evidence": "Firewall log: HTTPS POST to api.openai.com from OT workstation 10.0.3.60, payload contains alarm codes and setpoint data",
            },
        ],
    )


def get_environments(scenario_filter: str = "all") -> List[AIEnvironment]:
    """Get demo environments based on filter."""
    builders = {
        "enterprise": _build_enterprise_scenario,
        "soc": _build_soc_scenario,
        "ot": _build_ot_ics_scenario,
    }

    if scenario_filter == "all":
        return [builder() for builder in builders.values()]
    elif scenario_filter in builders:
        return [builders[scenario_filter]()]
    else:
        raise ValueError("Unknown scenario: {}. Options: {}".format(
            scenario_filter, list(builders.keys())
        ))
